import Head from 'next/head'
import Navbar from './components/Navbar'
import Header from './components/Header'
import Clients from './components/main/Clients'
import Feature from './components/main/Feature'
import local from 'next/font/local'
import Footer from './components/Footer'
import Team from './components/main/Team'
import Overview from './components/main/Overview'

const Basement = local ({src: '../public/fonts/BasementGrotesque.otf'})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main className={Basement.className}>
<Navbar />
 <Header title="big or small" subTitle="the great never settle for good"/>
 <Clients />
 <Feature />
 <Team name1="Team" name2="focuses" name3="results"/>
 <Overview />
</main>

<footer>
  <Footer />
</footer>
    </>
  )
}
