import Head from "next/head";
import Navbar from "./components/Navbar";
import Header from "./components/Header";
import Clients from "./components/main/Clients";
import Feature from "./components/main/Feature";
import local from "next/font/local";
import Footer from "./components/Footer";
import Team from "./components/main/Team";
import Overview from "./components/main/Overview";
import ScrollButton from "./components/main/ScrollButton";
import { Link } from "react-scroll";

const Basement = local({ src: "../public/fonts/BasementGrotesque.otf" });

export default function Home() {
  return (
    <div className="scroll">
      <Head>
        <title>AlphaSquad4.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* <ScrollButton /> */}
      <main className={Basement.className}>
        <Navbar name="light-wrap" none="none" logo={[        <Link to="Header" spy={true} smooth={true} offset={-150}>
          <img src="../images/logoalpha.svg" className="w-8" />
        </Link>]}/>
        <Header
          title="big or small"
          subTitle="the great never settle for good"
        />
        <Clients />
        <Feature />
        <Overview />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
}
